[package]
name = "osu-server-switcher"
version = "0.1.0"
description = "A tool for automatically switching logins when changing osu servers"
repository = "https://github.com/DiamondMiner88/osu-server-account-switcher"
authors = ["Diamond (https://github.com/DiamondMiner88)"]
license-file = "LICENSE"
edition = "2021"

[dependencies]
seahorse = "2.1"
whoami = "1.2.1"
rust-ini = "0.18.0"
osu-db = { version = "0.3.0", default-features = false }
