[package]
name = "osu-switcher"
version = "1.1.0"
description = "A tool for automatically switching server (+accounts)"
repository = "https://github.com/DiamondMiner88/osu-server-account-switcher"
authors = ["Diamond (https://github.com/DiamondMiner88)"]
license-file = "LICENSE"
edition = "2021"

[dependencies]
mslnk = "0.1.7"
seahorse = "2.1"
whoami = "1.2.1"
rust-ini = "0.18.0"
osu-db = { version = "0.3.0", default-features = false }
