on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-pc-windows-msvc
          override: true

      - name: Rust caching
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            $GITHUB_WORKSPACE/lib/rust/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('lib/rust/Cargo.lock') }}

      - name: Build release
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=x86_64-pc-windows-msvc

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: osu-server-switcher
          path: target/release/osu-server-switcher.exe
